apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2deploy
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/electron1162/hello-world.git'
    path: "." 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
